name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: |
        cd cmd
        go build -v -o protocol-plugin-santak-rtu
        ls -l protocol-plugin-santak-rtu  # 确保文件存在

    - name: Test
      run: |
        cd cmd
        go test -v

    - name: Check build artifact path
      run: |
        ls -l cmd/

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: protocol-plugin-santak-rtu_${{ matrix.goos }}_${{ matrix.goarch }}
        path: cmd/protocol-plugin-santak-rtu
        if-no-files-found: warn
